Page on Global.health
OxfordRSE/website pull request #64
Opened 2020-09-18 15:45 UTC by iamleeg

2020-09-18 16:43 UTC, martinjrobins requested changes
looks great @iamleeg, might want to put in a link to Global.health?

2020-09-18 16:43 UTC, martinjrobins commented on content/projects/2020_global_dot_health.md
> +The rapid global spread of the COVID-19 pandemic overwhelmed both the manual processes used by the Healthmap team, and the digital infrastructure used to record the data. A collaboration between BCH,
is there a link to Global.health, or at least a link to more info about it?

2020-09-18 17:02 UTC, abhidg commented on content/projects/2020_global_dot_health.md
> +description: "Delivering a scalable platform for "
scalable platform from global health?

2020-09-21 13:11 UTC, iamleeg commented on content/projects/2020_global_dot_health.md
> +The rapid global spread of the COVID-19 pandemic overwhelmed both the manual processes used by the Healthmap team, and the digital infrastructure used to record the data. A collaboration between BCH,
Yes, I added the links.

2020-09-21 13:11 UTC, iamleeg commented on content/projects/2020_global_dot_health.md
> +description: "Delivering a scalable platform for "
Oops :)

2020-09-21 15:57 UTC, merged